export interface KioskRegisteredUser {
  userId: string;
  phoneNumber: string;
  displayName: string;
  fullName?: string;
  avatar?: string;
  role?: string;
  registeredAt: number;
}

const STORAGE_KEYS = {
  DEVICE_TOKEN: 'kiosk_device_token',
  REGISTERED_USERS: 'kiosk_registered_users',
} as const;

export function formatPhoneNumber(phone: string): string {
  if (!phone) return '';
  return phone.replace(/^\+84/, '0').trim();
}

export function maskPhoneNumber(phone: string): string {
  const clean = formatPhoneNumber(phone);
  if (clean.length < 9) return clean;
  return `${clean.slice(0, 3)}••••${clean.slice(-3)}`;
}

export function generateAvatarGradient(identifier: string): string {
  let hash = 0;
  for (let i = 0; i < identifier.length; i++) {
    hash = identifier.charCodeAt(i) + ((hash << 5) - hash);
  }

  const gradients = [
    'from-emerald-600 to-teal-800',
    'from-blue-600 to-indigo-800',
    'from-violet-600 to-purple-800',
    'from-amber-600 to-orange-800',
    'from-rose-600 to-pink-800',
    'from-cyan-600 to-blue-800',
  ];

  const index = Math.abs(hash) % gradients.length;
  return gradients[index];
}

/** RFC 4122 UUID v4 regex — used to validate tokens read from localStorage. */
const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Generates a RFC 4122 UUID v4 without relying on crypto.randomUUID.
 * Used as fallback for HTTP pages or legacy browsers where crypto.randomUUID
 * may not be available.
 */
function generateUUIDv4Fallback(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/** Returns true if the given string is a valid UUID v4. */
function isValidUUIDv4(value: string): boolean {
  return UUID_V4_REGEX.test(value);
}

export const KIOSK_STORAGE_EVENT = 'kiosk-storage-change';

function notifyKioskStorageChange(key?: string): void {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent(KIOSK_STORAGE_EVENT, { detail: { key } }));
  }
}

export function subscribeToKioskStorage(callback: () => void): () => void {
  if (typeof window === 'undefined') return () => {};

  const handleStorage = (e: StorageEvent) => {
    if (!e.key || e.key.startsWith('kiosk_')) {
      callback();
    }
  };

  const handleCustomEvent = () => {
    callback();
  };

  window.addEventListener('storage', handleStorage);
  window.addEventListener(KIOSK_STORAGE_EVENT, handleCustomEvent);

  return () => {
    window.removeEventListener('storage', handleStorage);
    window.removeEventListener(KIOSK_STORAGE_EVENT, handleCustomEvent);
  };
}

export const kioskStorage = {
  /**
   * Returns the persistent UUID v4 device token stored in localStorage.
   *
   * IMPORTANT: must only be called on the client-side (after hydration).
   * Calling this during SSR (window === undefined) will throw to prevent
   * an empty string being sent to the API and causing a 400 Bad Request.
   */
  getDeviceToken(): string {
    if (typeof window === 'undefined') {
      throw new Error(
        '[kioskStorage] getDeviceToken() must be called on the client side only. ' +
        'Ensure this is invoked inside a useEffect, event handler, or "use client" component after hydration.',
      );
    }
    let token = localStorage.getItem(STORAGE_KEYS.DEVICE_TOKEN);

    // Validate the stored token. Legacy tokens (e.g. "1786165676498-vtikxax5i"
    // generated by the old Date.now() fallback) are not UUID v4-compliant and
    // must be discarded so a valid token is generated in their place.
    if (token && !isValidUUIDv4(token)) {
      console.warn(
        `[kioskStorage] Stale/invalid deviceToken found in localStorage ("${token}"). ` +
        'Regenerating a valid UUID v4.',
      );
      localStorage.removeItem(STORAGE_KEYS.DEVICE_TOKEN);
      token = null;
    }

    if (!token) {
      // Prefer the native crypto API (available on HTTPS); fall back to a
      // hand-rolled RFC 4122 v4 generator for HTTP or older environments.
      token =
        typeof crypto?.randomUUID === 'function'
          ? crypto.randomUUID()
          : generateUUIDv4Fallback();
      localStorage.setItem(STORAGE_KEYS.DEVICE_TOKEN, token);
      notifyKioskStorageChange(STORAGE_KEYS.DEVICE_TOKEN);
    }
    return token;
  },

  getRegisteredUsers(): KioskRegisteredUser[] {
    if (typeof window === 'undefined') return [];
    try {
      const raw = localStorage.getItem(STORAGE_KEYS.REGISTERED_USERS);
      return raw ? JSON.parse(raw) : [];
    } catch {
      return [];
    }
  },

  addRegisteredUser(user: {
    userId: string;
    phoneNumber: string;
    fullName?: string | null;
    avatar?: string | null;
    role?: string | null;
  }): void {
    if (typeof window === 'undefined') return;
    const users = kioskStorage.getRegisteredUsers();
    const existingIdx = users.findIndex((u) => u.userId === user.userId);
    const resolvedFullName = user.fullName?.trim() || undefined;
    const entry: KioskRegisteredUser = {
      userId: user.userId,
      phoneNumber: user.phoneNumber,
      fullName: resolvedFullName,
      displayName: resolvedFullName || maskPhoneNumber(user.phoneNumber),
      avatar: user.avatar || undefined,
      role: user.role || undefined,
      registeredAt: Date.now(),
    };

    if (existingIdx !== -1) {
      users[existingIdx] = {
        ...users[existingIdx],
        ...entry,
      };
    } else {
      users.push(entry);
    }

    localStorage.setItem(STORAGE_KEYS.REGISTERED_USERS, JSON.stringify(users));
    notifyKioskStorageChange(STORAGE_KEYS.REGISTERED_USERS);
  },

  updateRegisteredUserProfile(
    userId: string,
    updates: { fullName?: string | null; avatar?: string | null; role?: string | null }
  ): void {
    if (typeof window === 'undefined') return;
    const users = kioskStorage.getRegisteredUsers();
    const existingIdx = users.findIndex((u) => u.userId === userId);
    if (existingIdx === -1) return;

    const existing = users[existingIdx];
    const resolvedFullName =
      updates.fullName !== undefined ? updates.fullName?.trim() || undefined : existing.fullName;
    const resolvedAvatar =
      updates.avatar !== undefined ? updates.avatar || undefined : existing.avatar;
    const resolvedRole = updates.role !== undefined ? updates.role || undefined : existing.role;

    users[existingIdx] = {
      ...existing,
      fullName: resolvedFullName,
      displayName: resolvedFullName || maskPhoneNumber(existing.phoneNumber),
      avatar: resolvedAvatar,
      role: resolvedRole,
    };

    localStorage.setItem(STORAGE_KEYS.REGISTERED_USERS, JSON.stringify(users));
    notifyKioskStorageChange(STORAGE_KEYS.REGISTERED_USERS);
  },

  removeRegisteredUser(userId: string): void {
    if (typeof window === 'undefined') return;
    const users = kioskStorage.getRegisteredUsers().filter((u) => u.userId !== userId);
    localStorage.setItem(STORAGE_KEYS.REGISTERED_USERS, JSON.stringify(users));
    notifyKioskStorageChange(STORAGE_KEYS.REGISTERED_USERS);
  },

  removeDeviceToken(): void {
    if (typeof window === 'undefined') return;
    localStorage.removeItem(STORAGE_KEYS.DEVICE_TOKEN);
    notifyKioskStorageChange(STORAGE_KEYS.DEVICE_TOKEN);
  },

  hasRegisteredUser(userId: string): boolean {
    if (typeof window === 'undefined') return false;
    return kioskStorage.getRegisteredUsers().some((u) => u.userId === userId);
  },
};
