import { IsOptional, IsString, IsUUID, Length, Matches } from 'class-validator';

export class LoginDto {
  /** Vietnamese phone number in local format (0xxxxxxxxx) or E.164 format (+84xxxxxxxxx) */
  @IsString()
  @Matches(/^(0|\+84)[0-9]{9}$/, {
    message: 'phoneNumber must be a valid Vietnamese phone number (e.g. 0901234567 or +84901234567)',
  })
  phoneNumber!: string;

  /** 6-digit numeric PIN */
  @IsString() @Length(6, 6) @Matches(/^[0-9]{6}$/, { message: 'pin must be exactly 6 digits' }) pin!: string;

  /**
   * Optional UUID v4 device token from the kiosk browser's localStorage.
   * When provided, the device is automatically registered after successful login
   * so subsequent kiosk PIN logins work without a separate setup step.
   */
  @IsOptional()
  @IsUUID('4', { message: 'deviceToken must be a valid UUID v4' })
  deviceToken?: string;

  /**
   * Human-readable label auto-generated by the frontend from navigator.userAgent
   * (e.g. "Chrome on iPad"). Stored for admin device management visibility.
   */
  @IsOptional()
  @IsString()
  @Length(1, 150)
  deviceLabel?: string;
}

