persistence true
persistence_location /mosquitto/data/
log_dest stdout
connection_messages true
allow_anonymous false
listener 1883 0.0.0.0

auth_plugin /mosquitto/go-auth.so
auth_opt_backends http
auth_opt_http_host mushroom-backend
auth_opt_http_port 3001
auth_opt_http_getuser_uri /api/mqtt/auth
auth_opt_http_superuser_uri /api/mqtt/superuser
auth_opt_http_aclcheck_uri /api/mqtt/acl
auth_opt_http_params_mode form
auth_opt_http_response_mode status
auth_opt_http_timeout 5
auth_opt_cache true
auth_opt_cache_type go-cache
auth_opt_cache_refresh false
auth_opt_auth_cache_seconds 300
auth_opt_acl_cache_seconds 300
auth_opt_auth_jitter_seconds 0
auth_opt_acl_jitter_seconds 0
